# Generated by Django 4.2.2 on 2023-06-22 11:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=50)),
                ('is_visibility', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('platform', models.CharField(choices=[('PC', 'PC'), ('PS', 'PlayStation'), ('XBOX', 'Xbox'), ('IOS', 'iOS'), ('ANDROID', 'Android')], max_length=10)),
                ('params', models.JSONField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='product.game')),
            ],
        ),
    ]
