# Generated by Django 4.2.2 on 2023-07-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbase',
            name='user_id',
            field=models.UUIDField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='params',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='platform',
            field=models.CharField(default='PC', max_length=10),
        ),
    ]
