# Generated by Django 4.2.2 on 2023-07-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productbase_user_id_alter_productbase_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='params',
            field=models.JSONField(default=dict),
        ),
    ]
