# Generated by Django 4.2.2 on 2023-07-11 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_game_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbase',
            name='buyer_id',
            field=models.UUIDField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='productbase',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.productbase')),
            ],
        ),
    ]
