# Generated by Django 4.2.2 on 2023-07-15 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user_id', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acc_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='pay.useraccount')),
                ('acc_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='pay.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=50)),
                ('is_frozen', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('product_id', models.IntegerField()),
                ('acc_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_from', to='pay.useraccount')),
                ('acc_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_to', to='pay.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operation_type', models.CharField(max_length=50)),
                ('is_accept', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='pay.useraccount')),
            ],
        ),
    ]
